language: node_js
node_js:
  - '12'
notifications:
  email: false
deploy:
  on:
    branch: main
  provider: elasticbeanstalk
  access_key_id: AKIAIPOGQ6DIJQS2MSVQ
  secret_access_key:
    secure: 'X3NIL6u1hCNEpKOIFbNsEEYJksHUE00Ckttr2vwy5E1t364+h390niJ4z7gSjTlgF7YDHIGALJzgXQWqxRP8eZ0okPN7sywbOAsO4en4upAG97cR8GL6s+rh8R0e6LUpWb8szWzo+batk8nXBYp9beTMC9tLVeC/khXSPOu0CDAqKXkX85gOcUVJWsjnIZgVN8iS2ZxkTyCOFkxjeoufyVlnM0hHS2HHx1zJms0rJa/kYuUlM3URlDoYq3joeBqg0YIv1a6L36zAAotTs+hScupkIGmd8Oz4HETRB0CXnqHTJAAraG4ik5FFKLRZ+IC4/LMcTfA8zfxacLLonOkBiBs15k6agagis0QxHCDw+Gqs1R7gUS5KwGL8ASugTTvZCOA+WViNKLrWP7q0a+ubXSB/7fX4AzP45PubW9TAMbgydGhUXqTzMILEXPD3sE3tMdpTdc7bXv/P70AQIDDBCCVruodqVaKH5AIQCvCIL+fQeKxx256cBB8051GFQV5jO8EqzsbOF8E2MiO1QW4wZiUW/kf8JDiwP+MKjeMtoZ0LC1g7ab4KbFeilqTJ/prgq7aKjoLycDgx4bIrOLQ6mawAeSGmCm0kF/nIfzgOtHhDwfevPTV3xa9Zig3pB4oe9b51fLxeaZdBESTeQTSWLV9n1ui+fVPKtvGittGdTQs='
  region: 'us-east-1'
  app: 'test-node-app'
  env: 'Testnodeapp-env'
  bucket_name: 'test-node-S3-bucket'
