language: node_js
node_js:
  - '12'
notifications:
  email: false
deploy:
  on:
    branch: main
  provider: elasticbeanstalk
  access_key_id: AKIAJCC45WY2ETHOOVVA
  secret_access_key:
    secure: QNKWl1NlBIiKpR1ZEvFs2RiNPOCZhimqqDt4HpAcZV9ZDQmCWerylyYzRmsCHqqg1u6t4vnr23TbFf7RSbDrCypCBZ2pT0Dt3wyyzhvraabkojfi6lBeQu9nF6l5rKfnBWgqUPwW8q6thl0XHtGvh9/4nOXw+CYUHgRvWe26yeFTfli6zg7djMoPxjoLY5YOuk5M5ME+lLaM0GBfOu4MhUP0oMzHhT+/2pDjQk5xDOctttpVpu6+82xsUmFBaiBsn8SHPrYppYC/hjOR36G5mCcqtk5cLYpoWmGJC0V1uq9gbgsnbML8G5svCsqSkVfwDeNNyzmgM/CA+XOwDyQi6L9y34/TYKZNkTeVpbSmBF27RAV6V/jeuK3S7WONvybCDEQXWF4bYHsaUXmaH79Ttrzxp2Qnf36bB0LlXx/92shodh9OGKO8kPqCrT0RXT5MdmZnKs0S3j23mMq3Ow+70jLlZEtC6Xq6DvJGwGsnOkx/nWHzA/tF0oS6RcUMN/7xPi2XBMLsDP6PO+eQMZycvujMPqJolDShuEqLUx3b+VZDncSzAEG/ywIeiSnoyH3mAk04gIEUtxnRax0vtRH/6IMbu3bjCQPP1g8DJT2dIyuewHMCpv50wJANYq/k8rVyeHBlQ72A1zWmhzHRZtLBye0C2E0fFUMWVo3nSYWApEg=
  region: 'us-east-1'
  app: 'test-node-app'
  env: 'Testnodeapp-env'
  bucket_name: 'test-node-S3-bucket'
