language: node_js
node_js:
  - '12'
notifications:
  email: false
deploy:
  on:
    branch: main
  provider: elasticbeanstalk
  access_key_id: AKIAIPOGQ6DIJQS2MSVQ
  secret_access_key:
    secure: 'uyG2AtJ6IqaZfnqHB3x6Ma7w4A60ubv7V3m4JTrrFIFYB+fNjUMRRLnufx+xL2Chxo1eJr7+Ztug4yLDMe+EBTKHSmGmVXovuzaNollk+jljq0mqZWfe2srjpK7ykOkjM0N2SELJ+aSbxg9bbwCWOhCH/hCnKOP9Zw2X8iDHu/Sf6urrCF1HxKKOwSxU4pJ3DD+BusAT7xlaXEMw7chZlJjHP6zRYG9VrEuKIyE2/lsvnnihQg5lKjAIWaYTwcrt49W9qf3I1Ccw6i+0MoyUcy7xnCKTXLioLquHfCk/KaNzUCX5xP4xXldKKFcgGROoIdJxvvvrJNdnKjewHnxZRP5DFmpNo4q/Za4yIsDfOfV3fmpHmHn3E+Sg9l6udvYYjLZPPPN1TausoOCDNk6Okyldgs6YDORqDRRHKCOJllwv7HEQDvijJvvJtLkVw0kw+hxrKCWfEiW1DBqUPSZ2w/c4wRb2kBxetHrmNtxh4npnOzM4tjbajkuIHq7kduWPqufcdeexDMaSwOwIrp2iaFt5i2HnMvnb0TZygrzHhvtY7SWQtaOCA0EbU7va8JjDrvbsguhHkFvmiByrmFMlpB2bwRFAr+du+Lwp+L1dlI11TkFvx1qI6kOjeDZbyWCbLZ3nB8BrPxxxn83L3piyEhEjgikOJl+YKN8CsEvpfh8='
  region: 'us-east-1'
  app: 'test-node-app'
  env: 'Testnodeapp-env'
  bucket_name: 'elasticbeanstalk-us-east-1-189722766624'
